bootstrap: Show config.log on configure failure

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -858,6 +858,7 @@ for d in $modules ; do
       mkdir "$d"
     fi
     echo "Configuring \`$d'"
+    trap 'echo "configure failed, config.log was:";[ ! -f config.log ] || cat config.log' EXIT
     # Use a shared config.cache for speed and to save a bit of diskspace, but
     # don't share it with SWIG just in case it manages to probe and cache
     # different answers (e.g. because it uses a C compiler).
@@ -917,6 +918,7 @@ for d in $modules ; do
       cd "$d" && "$configure" --enable-maintainer-mode --disable-option-checking --cache-file="$here/config.cache" XAPIAN_CONFIG="$XAPIAN_CONFIG" XAPIANLETOR_CONFIG="$XAPIANLETOR_CONFIG" ${1+"$@"}
       ;;
     esac
+    trap 'echo "configure failed"' EXIT
     cd "$here"
     dirs="$dirs $d"
     revdirs="$d $revdirs"
