[ci] Re-enable mingw and cygwin jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -85,6 +85,419 @@ jobs:
       # if that input is empty.
       run: git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
 
+  mingw64-i686-cross:
+    runs-on: 'ubuntu-22.04'
+    needs: makedist
+    steps:
+    - name: Install CCache
+      uses: hendrikmuhs/ccache-action@v1
+      with:
+        key: ${{ github.job }}
+    - name: Fetch distribution
+      uses: actions/download-artifact@v4
+    - name: Unpack distribution
+      run: |
+        mv artifact/* .
+        rmdir artifact
+        pushd xapian-core
+        tar --strip-components=1 -xf xapian-core-*.tar.xz
+        popd
+        pushd xapian-letor
+        tar --strip-components=1 -xf xapian-letor-*.tar.xz
+        popd
+    - name: Install package dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install \
+            g++-mingw-w64-i686-win32 \
+            mingw-w64-i686-dev \
+            binutils-mingw-w64-i686 \
+            libz-mingw-w64-dev \
+            mingw-w64-tools
+    - name: configure
+      run: |
+        export EATMYDATA=
+        export PATH=/usr/lib/ccache:$PATH
+        pushd xapian-core
+        ./configure --enable-werror --host i686-w64-mingw32
+        export XAPIAN_CONFIG=$PWD/xapian-config
+        popd
+        pushd xapian-letor
+        ./configure --enable-werror --host i686-w64-mingw32
+        popd
+    - name: make
+      run: |
+        export PATH=/usr/lib/ccache:$PATH
+        make -j2 -C xapian-core
+        make -j2 -C xapian-letor
+    - name: Run tests
+      run: |
+        # Stop mono binfmt trying to run .exe files.
+        sudo apt-get purge mono-runtime
+        sudo dpkg --add-architecture i386
+        sudo apt-get update
+        sudo apt-get install wine32 wine-binfmt:amd64 wine:amd64
+        export AUTOMATED_TESTING=1
+        export VERBOSE=1
+        export WINEPATH="$PWD/xapian-core/.libs;/usr/lib/gcc/i686-w64-mingw32/`i686-w64-mingw32-g++ --version 2>/dev/null|head -n1|sed 's/.*) //;s/ .*//'`"
+        make -j2 -C xapian-core check
+        export WINEPATH="$PWD/xapian-letor/.libs;$WINEPATH"
+        make -j2 -C xapian-letor check
+
+  mingw64-x86-64-cross:
+    runs-on: 'ubuntu-22.04'
+    needs: makedist
+    steps:
+    - name: Install CCache
+      uses: hendrikmuhs/ccache-action@v1
+      with:
+        key: ${{ github.job }}
+    - name: Fetch distribution
+      uses: actions/download-artifact@v4
+    - name: Unpack distribution
+      run: |
+        mv artifact/* .
+        rmdir artifact
+        pushd xapian-core
+        tar --strip-components=1 -xf xapian-core-*.tar.xz
+        export XAPIAN_CONFIG=$PWD/xapian-config
+        popd
+        pushd xapian-letor
+        tar --strip-components=1 -xf xapian-letor-*.tar.xz
+        popd
+    - name: Install package dependencies
+      run: |
+        sudo apt-get update
+        # Stop mono binfmt trying to run .exe files.
+        sudo apt-get purge mono-runtime
+        sudo apt-get install \
+            g++-mingw-w64-x86-64-win32 \
+            mingw-w64-x86-64-dev \
+            binutils-mingw-w64-x86-64 \
+            libz-mingw-w64-dev \
+            mingw-w64-tools \
+            wine-binfmt \
+            wine \
+            wine64
+        sudo dpkg --add-architecture i386
+        sudo apt-get update
+        sudo apt-get install wine32
+    - name: configure
+      run: |
+        export EATMYDATA=
+        export PATH=/usr/lib/ccache:$PATH
+        pushd xapian-core
+        ./configure --enable-werror --host x86_64-w64-mingw32
+        export XAPIAN_CONFIG=$PWD/xapian-config
+        popd
+        pushd xapian-letor
+        ./configure --enable-werror --host x86_64-w64-mingw32
+        popd
+    - name: make
+      run: |
+        export PATH=/usr/lib/ccache:$PATH
+        make -j2 -C xapian-core
+        make -j2 -C xapian-letor
+    - name: Run tests
+      run: |
+        export AUTOMATED_TESTING=1
+        export VERBOSE=1
+        export WINEPATH="$PWD/xapian-core/.libs;/usr/lib/gcc/x86_64-w64-mingw32/`x86_64-w64-mingw32-g++ --version 2>/dev/null|head -n1|sed 's/.*) //;s/ .*//'`"
+        make -j2 -C xapian-core check
+        export WINEPATH="$PWD/xapian-letor/.libs;$WINEPATH"
+        make -j2 -C xapian-letor check
+
+  cygwin:
+    # We only test 64-bit cygwin as 32-bit support has been dropped as of
+    # Cygwin 3.4:
+    # https://cygwin.com/pipermail/cygwin/2022-November/252542.html
+    runs-on: 'windows-latest'
+    needs: makedist
+    defaults:
+      run:
+        # `-o incr` needed as GHA supplies shell fragments with DOS EOLs.
+        shell: 'C:\tools\cygwin\bin\bash.EXE --noprofile --norc -e -o igncr -o pipefail {0}'
+    steps:
+    - name: Install Cygwin
+      uses: egor-tensin/setup-cygwin@v4
+      with:
+        packages: gcc-g++ make file-devel libpcre2-devel zlib-devel perl
+    - name: Install CCache
+      uses: hendrikmuhs/ccache-action@v1
+      with:
+        key: ${{ github.job }}
+    - name: Fetch distribution
+      uses: actions/download-artifact@v4
+    - name: Unpack distribution
+      run: |
+        mv artifact/* .
+        rmdir artifact
+        pushd xapian-core
+        tar --strip-components=1 -xf xapian-core-*.tar.xz
+        popd
+        pushd xapian-applications/omega
+        tar --strip-components=1 -xf xapian-omega-*.tar.xz
+        popd
+        pushd xapian-bindings
+        tar --strip-components=1 -xf xapian-bindings-*.tar.xz
+        popd
+        pushd xapian-letor
+        tar --strip-components=1 -xf xapian-letor-*.tar.xz
+        popd
+    - name: configure
+      run: |
+        export CC='ccache gcc'
+        export CXX='ccache g++'
+        pushd xapian-core
+        ./configure --enable-werror
+        export XAPIAN_CONFIG=$PWD/xapian-config
+        popd
+        pushd xapian-applications/omega
+        ./configure --enable-werror
+        popd
+        # pushd xapian-bindings
+        # ./configure --enable-werror
+        # popd
+        pushd xapian-letor
+        ./configure --enable-werror
+        popd
+    - name: make
+      run: |
+        make -j2 -C xapian-core
+        make -j2 -C xapian-applications/omega
+        # make -j2 -C xapian-bindings
+        make -j2 -C xapian-letor
+    - name: Run tests
+      run: |
+        export AUTOMATED_TESTING=1
+        export VERBOSE=1
+        make -j2 -C xapian-core check
+        make -j2 -C xapian-applications/omega check
+        # make -j2 -C xapian-bindings check
+        make -j2 -C xapian-letor check
+
+  msys2-mingw32:
+    runs-on: 'windows-latest'
+    needs: makedist
+    defaults:
+      run:
+        shell: msys2 {0}
+    steps:
+    - uses: msys2/setup-msys2@v2
+      with:
+        msystem: mingw32
+        install: base-devel
+        pacboy: >-
+          file:p
+          gcc:p
+          pcre2:p
+          zlib:p
+    - name: Install CCache
+      uses: hendrikmuhs/ccache-action@v1
+      with:
+        key: ${{ github.job }}
+        variant: sccache
+    - name: Fetch distribution
+      uses: actions/download-artifact@v4
+    - name: Unpack distribution
+      run: |
+        mv artifact/* .
+        rmdir artifact
+        pushd xapian-core
+        tar --strip-components=1 -xf xapian-core-*.tar.xz
+        popd
+        pushd xapian-applications/omega
+        tar --strip-components=1 -xf xapian-omega-*.tar.xz
+        popd
+        # pushd xapian-bindings
+        # tar --strip-components=1 -xf xapian-bindings-*.tar.xz
+        # popd
+        pushd xapian-letor
+        tar --strip-components=1 -xf xapian-letor-*.tar.xz
+        popd
+    - name: configure
+      run: |
+        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
+        export CC='sccache gcc'
+        export CXX='sccache g++'
+        pushd xapian-core
+        ./configure --enable-werror
+        export XAPIAN_CONFIG=$PWD/xapian-config
+        popd
+        pushd xapian-applications/omega
+        ./configure --enable-werror
+        popd
+        # pushd xapian-bindings
+        # ./configure --enable-werror
+        # popd
+        pushd xapian-letor
+        ./configure --enable-werror
+        popd
+    - name: make
+      run: |
+        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
+        make -j2 -C xapian-core
+        make -j2 -C xapian-applications/omega
+        # make -j2 -C xapian-bindings
+        make -j2 -C xapian-letor
+    - name: Run tests
+      run: |
+        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
+        export AUTOMATED_TESTING=1
+        export VERBOSE=1
+        make -j2 -C xapian-core check
+        make -j2 -C xapian-applications/omega check
+        # make -j2 -C xapian-bindings check
+        make -j2 -C xapian-letor check
+
+  msys2-mingw64:
+    runs-on: 'windows-latest'
+    needs: makedist
+    defaults:
+      run:
+        shell: msys2 {0}
+    steps:
+    - uses: msys2/setup-msys2@v2
+      with:
+        msystem: mingw64
+        install: base-devel
+        pacboy: >-
+          file:p
+          gcc:p
+          pcre2:p
+          zlib:p
+    - name: Install CCache
+      uses: hendrikmuhs/ccache-action@v1
+      with:
+        key: ${{ github.job }}
+        variant: sccache
+    - name: Fetch distribution
+      uses: actions/download-artifact@v4
+    - name: Unpack distribution
+      run: |
+        mv artifact/* .
+        rmdir artifact
+        pushd xapian-core
+        tar --strip-components=1 -xf xapian-core-*.tar.xz
+        popd
+        pushd xapian-applications/omega
+        tar --strip-components=1 -xf xapian-omega-*.tar.xz
+        popd
+        # pushd xapian-bindings
+        # tar --strip-components=1 -xf xapian-bindings-*.tar.xz
+        # popd
+        pushd xapian-letor
+        tar --strip-components=1 -xf xapian-letor-*.tar.xz
+        popd
+    - name: configure
+      run: |
+        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
+        export CC='sccache gcc'
+        export CXX='sccache g++'
+        pushd xapian-core
+        ./configure --enable-werror
+        export XAPIAN_CONFIG=$PWD/xapian-config
+        popd
+        pushd xapian-applications/omega
+        ./configure --enable-werror
+        popd
+        # pushd xapian-bindings
+        # ./configure --enable-werror
+        # popd
+        pushd xapian-letor
+        ./configure --enable-werror
+        popd
+    - name: make
+      run: |
+        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
+        make -j2 -C xapian-core
+        make -j2 -C xapian-applications/omega
+        # make -j2 -C xapian-bindings
+        make -j2 -C xapian-letor
+    - name: Run tests
+      run: |
+        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
+        export AUTOMATED_TESTING=1
+        export VERBOSE=1
+        make -j2 -C xapian-core check
+        make -j2 -C xapian-applications/omega check
+        # make -j2 -C xapian-bindings check
+        make -j2 -C xapian-letor check
+
+  msys2-ucrt64:
+    runs-on: 'windows-latest'
+    needs: makedist
+    defaults:
+      run:
+        shell: msys2 {0}
+    steps:
+    - uses: msys2/setup-msys2@v2
+      with:
+        msystem: ucrt64
+        install: base-devel
+        pacboy: >-
+          gcc:p
+          zlib:p
+    - name: Install CCache
+      uses: hendrikmuhs/ccache-action@v1
+      with:
+        key: ${{ github.job }}
+        variant: sccache
+    - name: Fetch distribution
+      uses: actions/download-artifact@v4
+    - name: Unpack distribution
+      run: |
+        mv artifact/* .
+        rmdir artifact
+        pushd xapian-core
+        tar --strip-components=1 -xf xapian-core-*.tar.xz
+        popd
+        # pushd xapian-applications/omega
+        # tar --strip-components=1 -xf xapian-omega-*.tar.xz
+        # popd
+        # pushd xapian-bindings
+        # tar --strip-components=1 -xf xapian-bindings-*.tar.xz
+        # popd
+        pushd xapian-letor
+        tar --strip-components=1 -xf xapian-letor-*.tar.xz
+        popd
+    - name: configure
+      run: |
+        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
+        export CC='sccache gcc'
+        export CXX='sccache g++'
+        pushd xapian-core
+        ./configure --enable-werror
+        export XAPIAN_CONFIG=$PWD/xapian-config
+        popd
+        # FIXME: Fails to find magic.h for some reason even though it is
+        # installed via file:p above.
+        # pushd xapian-applications/omega
+        # ./configure --enable-werror
+        # popd
+        # pushd xapian-bindings
+        # ./configure --enable-werror
+        # popd
+        pushd xapian-letor
+        ./configure --enable-werror
+        popd
+    - name: make
+      run: |
+        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
+        make -j2 -C xapian-core
+        # make -j2 -C xapian-applications/omega
+        # make -j2 -C xapian-bindings
+        make -j2 -C xapian-letor
+    - name: Run tests
+      run: |
+        PATH=/c/Users/runneradmin/.cargo/bin:$PATH
+        export AUTOMATED_TESTING=1
+        export VERBOSE=1
+        make -j2 -C xapian-core check
+        # make -j2 -C xapian-applications/omega check
+        # make -j2 -C xapian-bindings check
+        make -j2 -C xapian-letor check
+
   msvc2019:
     runs-on: 'windows-2019'
     needs: makedist
