Compare rsync and sshfs on freebsd

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2490,7 +2490,6 @@ jobs:
           **/*.log
 
   freebsd:
-    if: false
     runs-on: 'ubuntu-22.04'
     needs: makedist
     steps:
@@ -2526,6 +2525,81 @@ jobs:
           export TCLSH=tclsh8.6
           mv xapian-* "$HOME"
           cd
+          cd xapian-core
+          tar --strip-components=1 -xf xapian-core-*.tar.xz
+          ./configure --enable-werror
+          export XAPIAN_CONFIG=$PWD/xapian-config
+          cd ..
+          cd xapian-applications/omega
+          tar --strip-components=1 -xf xapian-omega-*.tar.xz
+          ./configure --enable-werror
+          cd ../..
+          cd xapian-bindings
+          tar --strip-components=1 -xf xapian-bindings-*.tar.xz
+          ./configure --enable-werror --with-java --with-lua --with-perl --with-php --with-python3 --with-ruby --with-tcl
+          cd ..
+          cd xapian-letor
+          tar --strip-components=1 -xf xapian-letor-*.tar.xz
+          ./configure --enable-werror
+          cd ..
+          # Everything gets run in one script so use V=0 to reduce the size of
+          # the log, but re-run without V=0 on failure to show the compiler
+          # command line.
+          make -j2 -C xapian-core V=0 || make -C xapian-core
+          make -j2 -C xapian-applications/omega V=0 || make -C xapian-applications/omega
+          make -j2 -C xapian-bindings V=0 || make -C xapian-bindings
+          make -j2 -C xapian-letor V=0 || make -C xapian-letor
+          export AUTOMATED_TESTING=1
+          export VERBOSE=1
+          make -j2 -C xapian-core check V=0
+          make -j2 -C xapian-applications/omega check V=0
+          make -j2 -C xapian-bindings check V=0
+          make -j2 -C xapian-letor check V=0
+    - name: Save log files
+      if: ${{ failure() }}
+      uses: actions/upload-artifact@v4
+      with:
+        name: logs-${{ github.job }}-${{ github.sha }}
+        overwrite: true
+        path: |
+          **/*.log
+
+  freebsd-sshfs:
+    runs-on: 'ubuntu-22.04'
+    needs: makedist
+    steps:
+    - name: Install CCache
+      uses: hendrikmuhs/ccache-action@v1
+      with:
+        key: ${{ github.job }}
+        restore-keys: freebsd
+    - name: Fetch distribution
+      uses: actions/download-artifact@v4
+    - name: Unpack distribution
+      run: |
+        mv artifact/* .
+        rmdir artifact
+        # Do actual unpacking in the VM, mostly to help reduce the size of the
+        # rsync output in the logs.
+    - uses: vmactions/freebsd-vm@v1
+      # Limit wasted resources if the VM action gets into an infinite loop.
+      timeout-minutes: 60
+      with:
+        sync: sshfs
+        # The default is csh!
+        usesh: true
+        prepare: |
+          set -e
+          pkg install -y bash ccache lua54 openjdk17 openjdk17-jre perl5 php82 pcre2 pkgconf py311-sphinx python3 ruby rubygem-rdoc rubygem-test-unit tcl86
+          ccache --set-config=cache_dir="$HOME/work/xapian/xapian/.ccache"
+          ccache --set-config=max_size='500M'
+          ccache --set-config=compression=true
+        run: |
+          set -e
+          export CC='ccache cc'
+          export CXX='ccache c++'
+          export JAVA_HOME=/usr/local/openjdk17
+          export TCLSH=tclsh8.6
           cd xapian-core
           tar --strip-components=1 -xf xapian-core-*.tar.xz
           ./configure --enable-werror
