fiddling

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1585,7 +1585,7 @@ jobs:
     - name: Install Cygwin
       uses: egor-tensin/setup-cygwin@v4
       with:
-        packages: gcc-g++ make file-devel libpcre2-devel zlib-devel perl
+        packages: gcc-g++ make file-devel libpcre2-devel zlib-devel perl ruby ruby-rdoc
     - name: Install CCache
       uses: hendrikmuhs/ccache-action@v1
       with:
@@ -1655,6 +1655,7 @@ jobs:
           file:p
           gcc:p
           pcre2:p
+          ruby:p
           zlib:p
     - name: Install CCache
       uses: hendrikmuhs/ccache-action@v1
@@ -1692,7 +1693,7 @@ jobs:
         #./configure --enable-werror
         #popd
         pushd xapian-bindings
-        ./configure --enable-werror
+        ./configure --enable-werror --with-ruby
         popd
         #pushd xapian-letor
         #./configure --enable-werror
@@ -1728,6 +1729,7 @@ jobs:
         pacboy: >-
           file:p
           gcc:p
+          lua:p
           pcre2:p
           zlib:p
     - name: Install CCache
@@ -1766,7 +1768,7 @@ jobs:
         #./configure --enable-werror
         #popd
         pushd xapian-bindings
-        ./configure --enable-werror
+        ./configure --enable-werror --with-lua
         popd
         #pushd xapian-letor
         #./configure --enable-werror
@@ -1803,6 +1805,7 @@ jobs:
           file:p
           gcc:p
           pcre2:p
+          python3:p
           zlib:p
     - name: Install CCache
       uses: hendrikmuhs/ccache-action@v1
@@ -1840,7 +1843,9 @@ jobs:
         #./configure --enable-werror
         #popd
         pushd xapian-bindings
-        ./configure --enable-werror
+        # perl fails dues to perl_langinfo.h trying to include langinfo.h.
+        grep -C4 -i langinfo D:/a/_temp/msys64/usr/lib/perl5/core_perl/CORE/perl_langinfo.h D:/a/_temp/msys64/usr/lib/perl5/core_perl/CORE/config.h || true
+        ./configure --enable-werror --enable-python3
         popd
         #pushd xapian-letor
         #./configure --enable-werror
@@ -2312,7 +2317,7 @@ jobs:
         usesh: true
         prepare: |
           set -e
-          pkg install -y bash ccache lua54 perl5 php82 pcre2 py311-sphinx python3 ruby
+          pkg install -y bash ccache lua54 perl5 php82 pcre2 pkgconf py311-sphinx python3 ruby
           ls -l /usr/bin/lua* /usr/local/bin/lua* || true
           ls -l /usr/bin/php* /usr/local/bin/php* || true
           ccache --set-config=cache_dir="$HOME/work/xapian/xapian/.ccache"
@@ -2322,8 +2327,8 @@ jobs:
           set -e
           export CC='ccache cc'
           export CXX='ccache c++'
-          mv xapian-* "$HOME"
-          cd
+          #mv xapian-* "$HOME"
+          #cd
           cd xapian-core
           tar --strip-components=1 -xf xapian-core-*.tar.xz
           ./configure --enable-werror
@@ -2335,7 +2340,8 @@ jobs:
           #cd ../..
           cd xapian-bindings
           tar --strip-components=1 -xf xapian-bindings-*.tar.xz
-          ./configure --enable-werror --with-lua --with-perl --with-php --with-python3 --with-ruby
+          ./configure --enable-werror --with-lua --with-perl --with-php --with-python3 --with-ruby \
+            LUA=lua54
           cd ..
           #cd xapian-letor
           #tar --strip-components=1 -xf xapian-letor-*.tar.xz
@@ -2387,7 +2393,7 @@ jobs:
         usesh: true
         prepare: |
           set -e
-          pkg install -y bash ccache lua54 perl5 php82 pcre2 py39-sphinx python3 ruby
+          pkg install -y bash ccache lua54 perl5 php82 pcre2 pkconf py39-sphinx python3 ruby
           ls -l /usr/bin/lua* /usr/local/bin/lua* || true
           ls -l /usr/bin/php* /usr/local/bin/php* || true
           ccache --set-config=cache_dir="$HOME/work/xapian/xapian/.ccache"
@@ -2397,8 +2403,8 @@ jobs:
           set -e
           export CC='ccache cc'
           export CXX='ccache c++'
-          mv xapian-* "$HOME"
-          cd
+          #mv xapian-* "$HOME"
+          #cd
           cd xapian-core
           tar --strip-components=1 -xf xapian-core-*.tar.xz
           ./configure --enable-werror
@@ -2463,13 +2469,14 @@ jobs:
         # usesh: true
         prepare: |
           set -e
-          /usr/sbin/pkg_add -u ccache lua54 perl pcre2
+          /usr/sbin/pkg_add -u ccache lua54 perl pcre2 pkgconf
           # used by textproc/csharp-xapian/Makefile
           # used by textproc/lua-xapian/Makefile
           # used by textproc/p5-Xapian/Makefile
           # used by textproc/php-xapian/Makefile
           # used by textproc/py-xapian/Makefile
           # used by textproc/ruby-xapian/Makefile
+          ls -l /usr/bin/lua* /usr/local/bin/lua* /opt/bin/lua* || true
           ccache --set-config=cache_dir="$HOME/work/xapian/xapian/.ccache"
           ccache --set-config=max_size='500M'
           ccache --set-config=compression=true
@@ -2478,8 +2485,9 @@ jobs:
           ulimit
           export CC='ccache cc'
           export CXX='ccache c++'
-          mv xapian-* "$HOME"
-          cd
+
+          #mv xapian-* "$HOME"
+          #cd
           cd xapian-core
           tar --strip-components=1 -xf xapian-core-*.tar.xz
           ./configure --enable-werror
@@ -2511,7 +2519,7 @@ jobs:
           make -j2 -C xapian-bindings check V=0
           #make -j2 -C xapian-letor check V=0
           # Avoid bloating output with a huge file tree visualisation.
-          find xapian-* -depth \( -type f \! -name '*.log' -delete \) -or \( -type d -empty -delete \)
+          find xapian-* -depth \( -type f \! -name '*.log' \) -or \( -type d -empty \) -delete
     - name: Save log files
       if: ${{ failure() }}
       uses: actions/upload-artifact@v4
