Check lseek on mingw

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,171 +22,139 @@ on:
   workflow_dispatch:
 
 jobs:
-  makedist:
-    name: 'make dist'
-    runs-on: 'ubuntu-latest'
-    env:
-      LIBEXTRACTOR_PREFIX: '/usr/lib/x86_64-linux-gnu/libextractor'
-    steps:
-    - name: Check out repository code
-      uses: actions/checkout@v4
-      with:
-        show-progress: false
-    - name: Install CCache
-      uses: hendrikmuhs/ccache-action@v1
-      with:
-        key: ${{ github.job }}
-    - name: Cache bootstrap tools
-      uses: actions/cache@v4
-      with:
-        path: |
-          BUILD
-          INST
-        key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles( 'bootstrap', 'patches/**' ) }}
-    - name: Install package dependencies
-      run: |
-        sudo apt-get update
-        sudo apt-get install \
-            doxygen \
-            graphviz \
-            help2man \
-            python3-docutils \
-            pngcrush \
-            python3-sphinx \
-            uuid-dev \
-            libpcre2-dev \
-            libmagic-dev \
-            lua5.4 \
-            liblua5.4-dev \
-            mono-devel \
-            python3-dev \
-            tcl \
-            tcl-dev \
-            libicu-dev \
-            pkg-config \
-            libpoppler-glib-dev \
-            libglib2.0-dev \
-            libe-book-dev \
-            libetonyek-dev \
-            libgepub-0.6-dev \
-            libgmime-3.0-dev \
-            libarchive-dev \
-            libabw-dev \
-            libcdr-dev \
-            libextractor-dev \
-            libextractor-plugins-all \
-            libmwaw-dev \
-            libreofficekit-dev libreoffice-calc libreoffice-draw libreoffice-impress libreoffice-writer \
-            libtesseract-dev \
-            tesseract-ocr-eng
-    - name: bootstrap source tree
-      run: |
-        # If we restored cached bootstrap tools their timestamps will be older
-        # than checked out files, but we stored them based on a hash of the
-        # files in git that determine what gets built so we know they are in
-        # fact up to date.  Just touch any stamp files that exist.
-        touch --no-create INST/*.stamp
-        export PATH=/usr/lib/ccache:$PATH
-        echo verbose=off > ~/.wgetrc
-        ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
-    - name: configure
-      run: ./configure CC='ccache gcc' CXX='ccache g++' CXXFLAGS=-O0
-    - name: make
-      run: make -j2
-    - name: Create distribution tarball
-      run: |
-        make dist
-    - uses: actions/upload-artifact@v4
-      with:
-        path: |
-          xapian-core/xapian-core-*.tar.xz
-          xapian-applications/omega/xapian-omega-*.tar.xz
-          xapian-bindings/xapian-bindings-*.tar.xz
-          xapian-letor/xapian-letor-*.tar.xz
-        # Files are already compressed so don't try to compress again.
-        compression-level: 0
-        retention-days: 1
-        if-no-files-found: error
-    - name: Check generated files are in .gitignore
-      # grep '^' passes through all input while giving a non-zero exit status
-      # if that input is empty.
-      run: git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
+#  makedist:
+#    name: 'make dist'
+#    runs-on: 'ubuntu-latest'
+#    env:
+#      LIBEXTRACTOR_PREFIX: '/usr/lib/x86_64-linux-gnu/libextractor'
+#    steps:
+#    - name: Check out repository code
+#      uses: actions/checkout@v4
+#      with:
+#        show-progress: false
+#    - name: Install CCache
+#      uses: hendrikmuhs/ccache-action@v1
+#      with:
+#        key: ${{ github.job }}
+#    - name: Cache bootstrap tools
+#      uses: actions/cache@v4
+#      with:
+#        path: |
+#          BUILD
+#          INST
+#        key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles( 'bootstrap', 'patches/**' ) }}
+#    - name: Install package dependencies
+#      run: |
+#        sudo apt-get update
+#        sudo apt-get install \
+#            doxygen \
+#            graphviz \
+#            help2man \
+#            python3-docutils \
+#            pngcrush \
+#            python3-sphinx \
+#            uuid-dev \
+#            libpcre2-dev \
+#            libmagic-dev \
+#            lua5.4 \
+#            liblua5.4-dev \
+#            mono-devel \
+#            python3-dev \
+#            tcl \
+#            tcl-dev \
+#            libicu-dev \
+#            pkg-config \
+#            libpoppler-glib-dev \
+#            libglib2.0-dev \
+#            libe-book-dev \
+#            libetonyek-dev \
+#            libgepub-0.6-dev \
+#            libgmime-3.0-dev \
+#            libarchive-dev \
+#            libabw-dev \
+#            libcdr-dev \
+#            libextractor-dev \
+#            libextractor-plugins-all \
+#            libmwaw-dev \
+#            libreofficekit-dev libreoffice-calc libreoffice-draw libreoffice-impress libreoffice-writer \
+#            libtesseract-dev \
+#            tesseract-ocr-eng
+#    - name: bootstrap source tree
+#      run: |
+#        # If we restored cached bootstrap tools their timestamps will be older
+#        # than checked out files, but we stored them based on a hash of the
+#        # files in git that determine what gets built so we know they are in
+#        # fact up to date.  Just touch any stamp files that exist.
+#        touch --no-create INST/*.stamp
+#        export PATH=/usr/lib/ccache:$PATH
+#        echo verbose=off > ~/.wgetrc
+#        ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
+#    - name: configure
+#      run: ./configure CC='ccache gcc' CXX='ccache g++' CXXFLAGS=-O0
+#    - name: make
+#      run: make -j2
+#    - name: Create distribution tarball
+#      run: |
+#        make dist
+#    - uses: actions/upload-artifact@v4
+#      with:
+#        path: |
+#          xapian-core/xapian-core-*.tar.xz
+#          xapian-applications/omega/xapian-omega-*.tar.xz
+#          xapian-bindings/xapian-bindings-*.tar.xz
+#          xapian-letor/xapian-letor-*.tar.xz
+#        # Files are already compressed so don't try to compress again.
+#        compression-level: 0
+#        retention-days: 1
+#        if-no-files-found: error
+#    - name: Check generated files are in .gitignore
+#      # grep '^' passes through all input while giving a non-zero exit status
+#      # if that input is empty.
+#      run: git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
 
-  netbsd-lseek-safety:
-    runs-on: 'ubuntu-22.04'
+  mingw-lseek-safety:
+    runs-on: 'windows-latest'
+    defaults:
+      run:
+        shell: msys2 {0}
     steps:
     - uses: actions/checkout@v4
-    - uses: vmactions/netbsd-vm@v1
-      # Limit wasted resources if the VM action gets into an infinite loop.
-      timeout-minutes: 60
+    - uses: msys2/setup-msys2@v2
       with:
-        # Default is ksh, which should be OK.
-        # usesh: true
-        run: |
-          set -e
-          cc -Wall -W lseek-safety-test.c
-          ./a.out TESTFILE
-          ls -l TESTFILE
-          du -k TESTFILE
-          rm -f a.out TESTFILE
+        msystem: ucrt64
+        install: base-devel
+        pacboy: >-
+          gcc:p
+    - name: test
+      run: |
+        gcc -Wall -W lseek-safety-test.c -o a.exe
+        ./a.exe TESTFILE
+        ls -l TESTFILE
 
   # opencsw's newest GCC is 5.5 which lack C++17 support.
   solaris:
     runs-on: 'ubuntu-22.04'
-    needs: makedist
+      #    needs: makedist
     steps:
     - name: Install CCache
       uses: hendrikmuhs/ccache-action@v1
       with:
         key: ${{ github.job }}
-    - name: Fetch distribution
-      uses: actions/download-artifact@v4
-    - name: Unpack distribution
-      run: |
-        mv artifact/* .
-        rmdir artifact
-        # Do actual unpacking in the VM, mostly to help reduce the size of the
-        # rsync output in the logs.
+#    - name: Fetch distribution
+#      uses: actions/download-artifact@v4
+#    - name: Unpack distribution
+#      run: |
+#        mv artifact/* .
+#        rmdir artifact
+#        # Do actual unpacking in the VM, mostly to help reduce the size of the
+#        # rsync output in the logs.
     - uses: vmactions/solaris-vm@v1
       # Limit wasted resources if the VM action gets into an infinite loop.
       timeout-minutes: 60
       with:
         release: "11.4-gcc"
-        prepare: |
-          set -e
-          pkgutil -y -i ccache gtar perl libpcre2_dev
-          ccache --set-config=cache_dir='/Users/runner/work/xapian/xapian/.ccache'
-          ccache --set-config=max_size='500M'
-          ccache --set-config=compression=true
         run: |
           set -e
           ulimit
-          export CC='ccache gcc'
-          export CXX='ccache g++'
-          cd xapian-core
-          gtar --strip-components=1 -xf xapian-core-*.tar.xz
-          ./configure --enable-werror
-          export XAPIAN_CONFIG=$PWD/xapian-config
-          cd ..
-          cd xapian-applications/omega
-          gtar --strip-components=1 -xf xapian-omega-*.tar.xz
-          ./configure --enable-werror
-          cd ../..
-          # cd xapian-bindings
-          # gtar --strip-components=1 -xf xapian-bindings-*.tar.xz
-          # cd ..
-          cd xapian-letor
-          gtar --strip-components=1 -xf xapian-letor-*.tar.xz
-          ./configure --enable-werror
-          cd ..
-          # Everything gets run in one script so use V=0 to reduce the size of
-          # the log, but re-run without V=0 on failure to show the compiler
-          # command line.
-          make -j2 -C xapian-core V=0 || make -C xapian-core
-          make -j2 -C xapian-applications/omega V=0 || make -C xapian-core
-          make -j2 -C xapian-letor V=0 || make -C xapian-letor
-          export AUTOMATED_TESTING=1
-          export VERBOSE=1
-          make -j2 -C xapian-core check V=0
-          make -j2 -C xapian-applications/omega check V=0
-          make -j2 -C xapian-letor check V=0
+          find / -name '*CC' -print
+          find / -name '*++*' -print
